### ISSUE TITLE
on the selected subpage

### ISSUE THREAD

**Issue by MrBartek007** [kpodemski/phfbchat#13]
Hej,
czy jest możliwość wyświetlenia phfbchat na wybranej podstronie? 

Hello,
is it possible to display phfbchat on the selected subpage?

**Comment by PrestaShark** [comment]
Hej. Szukając modułu w zaczepie "displayFooter" (Wygląd -> Pozycje) i edytując jego właściwości, możesz określić wykluczenia wyświetlania modułu w danych kontrolerach. Np wykluczyć go dla strony index, cms, order. Takie ustawienie spowoduje że moduł nie wyświetli się na:
stronie głównej (index)
cms (wszystkich stronach cms)
order (na stronie zamówienia)
itp itd.

Np tak:
![pozycje](https://user-images.githubusercontent.com/8243273/59504410-31555480-8ea3-11e9-9ad3-60e39d6615c2.jpg)

**Comment by MrBartek007** [comment]
Dzięki. :) Zapomniałem o tej możliwości!
