### ISSUE TITLE
Icon location on the page

### ISSUE THREAD

**Issue by tymosz99** [kpodemski/phfbchat#17]
Hello,
I have a question if there is a way for the widget to be on the left instead of the right.

**Comment by kpodemski** [comment]
Hello,

there's a way but it needs modifications of CSS, this free module is not designed to be on the left side

**Comment by tymosz99** [comment]
Could you do that for me? I think this is not a big problem.

**Comment by kpodemski** [comment]
No, sorry, you can ask on the official PrestaShop forum, maybe someone will have time to do that for you :)

**Comment by tymosz99** [comment]
oke, ty for help

**Comment by PrestaShark** [comment]
@tymosz99 just add this line in Your custom.css file

.fb_customer_chat_bounce_in_v2, .fb_dialog {left:1rem;}

Thats all
