### ISSUE TITLE
Zainstalowany - nie działa

### ISSUE THREAD

**Issue by szczemat** [kpodemski/phfbchat#18]
Cześć!
Ściągnąłem najnowszą wersję wtyczki, zainstalowałem, skonfigurowałem i plugin się nie wyświetla. 
FB również skonfigurowane poprawnie. Najnowsza PS na pokładzie z numerem 1.7.6 - będę wdzięczny za pomysły, co ewentualnie mogło pójść nie tak.

**Comment by szczemat** [comment]
English version below:

Hello!
I downloaded the latest version of the plugin, installed it, configured it and the plugin is not displayed.
FB also configured correctly. Latest PS on board with number 1.7.6 - I would be grateful for your ideas what could possibly go wrong.

**Comment by kpodemski** [comment]
Cześć,

jaki jest adres sklepu?

**Comment by szczemat** [comment]
To nasza strona testowa: 
`https://presta3.iform.com.pl/`

**Comment by kpodemski** [comment]
To wygląda tak jakbyście nie mieli hooka od footera w szablonie, bo moduł wcale się nie wczytuje, a jest (powinien) być przypięty do `displayFooter`

**Comment by szczemat** [comment]
Sprawdzam ustawienia w Preście i mam tak: 
![footer](https://user-images.githubusercontent.com/55784950/65587213-caf1cf00-df85-11e9-8775-ac246f25ca12.jpg)

**Comment by kpodemski** [comment]
Macie przypiętego hooka, ok, ale czy jest na pewno w szablonie? Nie ma tam jakiegoś page buildera/footer buildera, który zamiast `displayFooter` wyświetla swoje dane? :)
