### ISSUE TITLE
Browser compatibillity

### ISSUE THREAD

**Issue by wordliner** [kpodemski/phfbchat#19]
I can see module on Chrome, but not on Firefox or Edge.

Latest browsers. Latest prestashop.  PHP.7.2

https://systemowekominy.pl

**Comment by kpodemski** [comment]
Firefox has some "Do not track" mechanism in recent versions, this is why we have in the console information:
`Żądanie dostępu do ciasteczek lub danych stron pod adresem „https://connect.facebook.net/pl_PL/sdk/xfbml.customerchat.js” zostało zablokowane, ponieważ pochodziło od elementu śledzącego, a blokowanie treści jest włączone. `

it's hard to tell what to do in this scenario, i don't think it's possible to prevent this from happening
