### ISSUE TITLE
If not logged in into WebBrowser not able to see the messenger icon

### ISSUE THREAD

**Issue by cquesadad** [kpodemski/phfbchat#2]
Hello! Thanks for sharing it to the community. Im working with the module and I discover that when you are not logged in into facebook in an specific web browser the module and icon does not show itself. Any Idea? Thanks a lot!

**Comment by cquesadad** [comment]
Could be because the App is still waiting for approval?  You can write me to diseno@canariasexclusive.com

**Comment by kpodemski** [comment]
Hey @cquesadad 

to be honest your app doesn't need any special permissions, you should have it accepted very quick, if not, maybe you have asked for too many permissions

if someone is not logged in on Facebook, icon will appear, but the information about login will be available

**Comment by cquesadad** [comment]
Thanks for answering! Yes I'm already in the 2nd step of the approval of the app and the state is in development, is not live yet. In the website I can see the chat linked to that app ID just when Im Logged in to facebook in that web browser, if not logged in, I can't see any chat button or login info. Wy is that happening? Any Idea?

**Comment by kpodemski** [comment]
Maybe you're using some other modules which are related to facebook API?

**Comment by cquesadad** [comment]
Yes, indeed Im using the official Facebook Pixel. Is that a problem?

**Comment by kpodemski** [comment]
It may be a problem, i'll need to check. I'll get back to you later.

**Comment by cquesadad** [comment]
Thanks! No problem! I will be around!
