### ISSUE TITLE
Keeps opening at every page load

### ISSUE THREAD

**Issue by consochris** [kpodemski/phfbchat#21]
Hello, I have downloaded your module and installed it successfully. 
I feel it annoying that on every page load the messenger popup loads and open itself. Is this the normal behavior? How to change this?
Thanks in advance.
Chris

**Comment by PrestaShark** [comment]
https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/#customization You need to add "greeting_dialog_display" parameter to "false" as described

**Comment by consochris** [comment]
Thanks very much. Where should this parameter be added? On your module?

**Comment by PrestaShark** [comment]
In this file https://github.com/kpodemski/phfbchat/blob/master/views/templates/hook/footer.tpl compare code and replace the part at the bottom


```
<div class="fb-customerchat"
page_id="{$phfbchat_page_id}"
{if $phfbchat_logged_in}
logged_in_greeting="{$phfbchat_logged_in}"
{/if}
{if $phfbchat_logged_out}
logged_out_greeting="{$phfbchat_logged_out}"
{/if}
{if $phfbchat_theme_color}
theme_color="{$phfbchat_theme_color}"
{/if}
{if $phfbchat_greeting_dialog_delay}
greeting_dialog_delay="{$phfbchat_greeting_dialog_delay}"
{/if}
 greeting_dialog_display="hide" ></div>
```
Sometimes it takes some time to refresh that behavior https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/#caching but it works fine :)
