### ISSUE TITLE
Module reduces Pagespeed to half speed

### ISSUE THREAD

**Issue by renovatio118** [kpodemski/phfbchat#27]
Module works without issues in PrestaShop 1.7.5 in my case but it reduces page speed dramatically.
My average speed in Google PageSpeed Insights is 48. 
After i enabled the module, the speed dropped to 25. 
When i disabled it, it immediately came back to normal.

Any chance to make fixes? 

Thank you!

**Comment by PrestaShark** [comment]
It's not module fault but Facebook scripts and resources loaded to page to show FB Chat/Messenger.... :/

**Comment by kpodemski** [comment]
Like @PrestaShark said, it's not really fault of the module, of course there's a room for an improvement here but i'm not planning to do that.
