### ISSUE TITLE
Not working since PS update

### ISSUE THREAD

**Issue by LucasVollebergh** [kpodemski/phfbchat#28]
Hi,
Unfortunately the module stopped working since my updat to the newest prestashop version.
Can't see the icon anymore.

**Comment by LucasVollebergh** [comment]
HI, not sure why it suddenly stopped working. 
I have tried many thing, reinstalling, resetting, rehooking. 
Now after I changed language from nl_BE to nl_NL it works again, but can be something else.. Not sure this was the cause.

Highly suggest anyone with problems to check and recheck settings..... :)

**Comment by kpodemski** [comment]
Thanks for the suggestion :)
