### ISSUE TITLE
Nothing's showing

### ISSUE THREAD

**Issue by xsteacy** [kpodemski/phfbchat#3]
Hi,
I did everything that you wrote in the readme.md file. Just one thing, I put my ip and the one of my server  in the whitelist of the facebook DEV page, you we're not clear of what Facebook page it was question of.

If I see others comment that should be an icon for messenger on my website and I see nothing! I know how prestashop work and I didn't saw anything I can do.

Please, can you help me?.

**Comment by kpodemski** [comment]
Hello,

module has been updated to be compilant with new SDK, make sure to update it to v1.0.1

**Comment by TDRaF** [comment]
Same problem for me

**Comment by kpodemski** [comment]
Make sure to update module to the newest version

**Comment by kpodemski** [comment]
First of all. Update module.

Secondly, remember that you don't need to set up app anymore, you need to whitelist domain in your Facebook Page setting in Messenger section

**Comment by TDRaF** [comment]
I downloaded this: https://ibb.co/isgWHA

**Comment by kpodemski** [comment]
You need to download phfbchat-latest, install it, configure and set everything up on Facebook Page Settings

**Comment by TDRaF** [comment]
I have one problem with white-listed domains. I enter http://www.trendylt.lt <http://www.trendylt.lt/> but when I press enter it changes to https. Maybe you know why?
https://ibb.co/kKABjq
https://ibb.co/iFwTVV

**Comment by kpodemski** [comment]
Maybe https is required. I don't really know :)

**Comment by TDRaF** [comment]
I have SSL now and it is installed, but module still doesn’t work.

**Comment by PrestaShark** [comment]
Go to Your Facebook Fanpage settings and whitelist Your domain !

**Comment by PrestaShark** [comment]
![cmon](https://user-images.githubusercontent.com/8243273/48843433-5ebba300-ed97-11e8-9060-8d4dbdd90f22.jpg)

**Comment by TDRaF** [comment]
I have inserted APP ID but cannot see subscribed app. https://ibb.co/c5wRZq

**Comment by TDRaF** [comment]
Hi,

Can you help me?
