### ISSUE TITLE
Messenger Chat Not Working 

### ISSUE THREAD

**Issue by samthatguy88** [kpodemski/phfbchat#33]
Hi, 

I hope you are well. I installed the module several weeks ago and really cannot get it to work. 
I have input all of the information required in the Prestashop Back Office but cannot put my finger on why it is not working. 

Your help on this would be much appreciated. 

Kind Regards, 

Sam

**Comment by kpodemski** [comment]
Hello,

make sure that:
- you have a valid locale provided in module Settings
- domain whitelisted in your Facebook Page Settings
- valid Page ID provided
- newest version of the module

If you still have issues let me know and send me URL to your store
