### ISSUE TITLE
Disable automatice opening

### ISSUE THREAD

**Issue by KoreLewi** [kpodemski/phfbchat#34]
Hi,

I have installed the module, and its working as expected. Thank you!

I have only one problem. The module(the popup) is opening every time after the page load, and it's pretty confusing. 
There is any way to turn this feature off? And only open the messenger when we click on it the messenger icon?

Kind regards,
Levi

**Comment by Roller-BE** [comment]
Hello Levi,
Did you try to fix the "Dialog delay" parameter in module configuration time ?  
By the way, did you install the phfbchat-master or the phfbchat-latest module ? I've installed the second one, and I got no popup on page ...
![image](https://user-images.githubusercontent.com/74574742/99325524-d0d7fd00-2876-11eb-8f62-d73152607fb2.png)

**Comment by KoreLewi** [comment]
Hi,

Thank for the answer. I've installed to a "virgin" Prestashop, and its worked.
And I managed to fix it also on my shop, by adding the  greeting_dialog_display="hide" attribute

**Comment by kpodemski** [comment]
Hey guys,

it seems that performance optimization broke `delay` option completely but to be 100% honest I'm thinking about having hardcoded:
`greeting_dialog_display="hide"`

it's really annoying to have messenger chat popup :) what do you think?

**Comment by mostrolbud** [comment]
Hi, 
How Can I disable auto opening  on mobile devices?
