### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Dano7762** [kpodemski/phfbchat#36]
Hello,
Sorry for my bad english.

We installed your module on our prestashop v.1.7.6.9, and we configured our facebook page as you mentioned; but nothing is displayed on our site.
On facebook SDK version is 9 and on your module is 8, do you think it could be the problem ?

**Comment by kpodemski** [comment]
Hello,

make sure that:
- you have a valid locale provided in module Settings
- domain whitelisted in your Facebook Page Settings
- valid Page ID provided
- newest version of the module

If this still doesn't help send me URL to your store

**Comment by Dano7762** [comment]
Hello

We have done that like you can see on screenshots but still not work

URL of our website : https://2ms-creation.com/

**Comment by kpodemski** [comment]
You have invalid sdk included in your store:
<script async="" defer="" crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&amp;version=v3.3"></script>

If you want to use customer chat you need to remove this script.

**Comment by Dano7762** [comment]
Thank you for your answer but I don't know where I can remove it... I think this sdk was installed with a module but I don't know wich one  :/

**Comment by Dano7762** [comment]
I found it !

It was a module installed with my template : Simplio Sliding Facebook Fan Page

I have t find a new one for showing our facebook fan page on our store

Thank you for your help

**Comment by Dano7762** [comment]
Do you know how we can use these 2 modules ? :/

**Comment by kpodemski** [comment]
Just have only one sdk, this one from customer chat.
