### ISSUE TITLE
Doesn't work properly in mobile

### ISSUE THREAD

**Issue by dhwywy** [kpodemski/phfbchat#39]
When accessing my website mobile version, this facebook chat shows a small windows in the footer with some text (instead of the messenger icon only), and it breaks my website, users can't scroll down/up neither click in any button or link in the website.
When we click in the message, it shows up a popup with info about chat, then when we click the "X" (close button) the website works properly again and the popup disappears and then it shows the messenger rounded icon in the bottom.

That's weird...
Seems like the user has to click in that chat message to see some info, and then only after closing it they can navigate in the website.

**Comment by kpodemski** [comment]
Hello,

I have no such an issues on demo installation https://16.prestahomepreview.com/
