### ISSUE TITLE
Correct SDK src due to Facebook SDK changes

### ISSUE THREAD

**Issue by PrestaShark** [kpodemski/phfbchat#4]
Hi! Due Facebook changes please update SDK src.

##########################
#  The CustomerChat plugin will soon be removed from the main Facebook SDK.
#  To continue using it please use the correct SDK URL.
#  For more details see https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk
##########################

js.src = "//connect.facebook.net/{$phfbchat_locale}/all.js";

to

js.src = "//connect.facebook.net/{$phfbchat_locale}/sdk/xfbml.customerchat.js";

**Comment by Betoniara** [comment]
window.fbAsyncInit = function () {ldelim}
    FB.init({
        appId: {$phfbchat_app_id},
		autoLogAppEvents : true,
		xfbml            : true,
		version          : 'v3.1'
    {rdelim});

**Comment by kpodemski** [comment]
module has been updated
