### ISSUE TITLE
Not work :(

### ISSUE THREAD

**Issue by xianglmu** [kpodemski/phfbchat#40]
Hello!
I downloaded the latest version of the plugin, installed it, configured it and the plugin is not displayed.
FB also configured correctly. Hook is good.  I would be grateful for your ideas what could possibly go wrong.

https://lashmeup.pl/pl/

**Comment by kpodemski** [comment]
Hey,

I don't see HTML code from `phfbchat`, it might be related to your theme, few versions of footer, some page builder etc.

**Comment by xianglmu** [comment]
I guess I improved, could you please see again?

**Comment by kpodemski** [comment]
It seems that you have two separated Facebook SDK loaded on your site, there should be only one, customer chat.

**Comment by xianglmu** [comment]
Mam zainstalowany Facebook Connect od "hipresta" - czy może chodzić o to?

Podpowiesz jak mogę to poprawić?

**Comment by kpodemski** [comment]
Tak, to może być przez to, należy wywalić ładowanie SDK przez moduł hipresta, zostawić sam chat i dodać do inicjalizacji `appId: XXXXXXX` gdzie `XXXXXX` to oczywiście ID aplikacji do logowania

**Comment by xianglmu** [comment]
Wywaliłem ładowanie przez tamten moduł.

dodałem appID:
/sdk/xfbml.customerchat.js?appId=343650573434426

Rezultat: chat działa, jednak hipresta nie. Można na to cos poradzić?
