### ISSUE TITLE
can`t install

### ISSUE THREAD

**Issue by photinia73** [kpodemski/phfbchat#41]
Hello Krystian!
Can you help me to install your phfbchat, because the standart modules installation in the BO reported that the phfbchat-1.1.6.zip is not a real archive....

**Comment by kpodemski** [comment]
Hello!

Please install module by downloading it from here: https://github.com/kpodemski/phfbchat/blob/master/phfbchat-latest.zip

**Comment by photinia73** [comment]
I installed, but it not appear on the site/ the domain is on the white list
![image](https://user-images.githubusercontent.com/50954519/109856874-add52b80-7c62-11eb-9579-708983cb04f5.png)

Does it have metter, that I connect facebook Api on the https://developers.facebook.com? to my facebook page?

**Comment by kpodemski** [comment]
If you have more addons using Facebook you need to make sure that every one of them is using customer chat sdk JavaScript library to prevent any conflicts between them

**Comment by photinia73** [comment]
on the facebook page https://www.facebook.com/SvitlanaTopaz only one app conected
One other - this is facebook login connecting to the web page https://te.com.ua

**Comment by kpodemski** [comment]
You have few initializations of Facebook SDK in your store, example:
https://www.dropbox.com/s/m79b43c788p92cx/Zrzut%20ekranu%202021-03-3%20o%2020.05.23.png?dl=0

as I said earlier, it won't work this way, you need to have only one initialization or every one of them pointing to customer chat sdk, like this plugin does

**Comment by photinia73** [comment]
Ok I stoped the midule Facebook connect and your module appeared. I will donate you a coffee if you explaine me how to use different SDK, unfortunately I am not a developer

**Comment by kpodemski** [comment]
It's hard to help without access to help (but don't send it to me! :)) 

Basically you need to find a place where this code is available, you should be able to find a proper file after enabling developer mode in your shop, in Advanced Parameters -> Performance, then if you "Inspect" your site and search for `all.js` you should have path to file written as HTML comment.

If you still have no idea of what I'm talking about, don't worry, but I'd suggest to hire someone for you to do proper modifications 👍

**Comment by photinia73** [comment]
You know I spend 2 days to connect FB API to my  FB business page and now understood (thank yours few words) that the problem was in the other place )))  I have old module in my Themes and it also began work )) I think, that with your little help I have a chance to resolve this task ))
The biggest question - for what I connect FB Messenger App )))))

**Comment by photinia73** [comment]
I`m not sure that understood you right. But in the Debug mode I didn't found nothing about all.js

**Comment by photinia73** [comment]
May be you know the someone? who can help? Not very expencive )))
