### ISSUE TITLE
Need help, dont show

### ISSUE THREAD

**Issue by JuanKA1Casal** [kpodemski/phfbchat#50]
My web: https://www.aukas.cl/
Prestashop 1.6.1.18
Module position: displayFooter
Module v: 1.1.6

Setting:
Localization: es_ES
Page ID: 694650990562314
Dialog delay: 1

Facebook plugging chat setting:
Dominio de sitio web: http://www.aukas.com/, https://www.aukas.cl/

But nothing happens T.T

**Comment by kpodemski** [comment]
Hello,

I don't see the `phfbchat` module in the source code of your website. Are you sure the `displayFooter` hook is available in your theme? Very often, there's no `displayFooter` in custom themes but some dedicated hook related to some footer builder, etc.
