### ISSUE TITLE
Issues with the module - Doesnt show

### ISSUE THREAD

**Issue by caito103** [kpodemski/phfbchat#7]
Hi! I installed the module on my prestashop 1.7.2.1 and i have the last version of the module (1.1.0).

I added all the info that the module needs, and added the domain and Ip to the Facebook white-list.

I cleared the caché of the site, but still not showing the messenger icon.

site: https://poresoestoypobre.cl/

There still that im missing?

**Comment by fsadak** [comment]
Same here... 1.7.5.0

**Comment by PrestaShark** [comment]
Guys its pretty easy without any module. Just go to Your FP settings and generate widget from there... Copy code and paste to Your template. Thats all. Sorry Krystian ;)

**Comment by PrestaShark** [comment]
Everything is here

![zrzut 2019-01-09 15 16 40](https://user-images.githubusercontent.com/8243273/50904836-9ce15480-1421-11e9-9a32-e8e6dc56a1e2.png)

**Comment by fsadak** [comment]
Yes everything is there and i was using this method but since PrestaShop 1.7.3 doesn't work for me.

**Comment by jk444** [comment]
I use Prestashop 1.7.4.4. I confirm there is a problem somewhere the messenger chat doesn't appears

**Comment by TomaszSos** [comment]
There is a solution:
PrestaShop in 1.7.x version have a problem with one parameter => {$phfbchat_locale}.
In this plugin is:
js.src = 'https://connect.facebook.net/{$phfbchat_locale}/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';

If we change the parameters {$phfbchat_locale} to real localization, for example pl_PL - for Poland, like that:
js.src = 'https://connect.facebook.net/pl_PL/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';

this plugin works perfectly :-) and messenger plugin is appear :-)

**Comment by jk444** [comment]
Hi, thanks for your response, can you explain where to do this modification ?
Regards

**Comment by TomaszSos** [comment]
... find, where is the module is installed. 
In PrestaShop serwer. Path is: ../public_html/modules/phfbchat/views/templates/hook file footer.tpl

**Comment by fsadak** [comment]
Thank you. This method solved my problem... 

> There is a solution:
> PrestaShop in 1.7.x version have a problem with one parameter => {$phfbchat_locale}.
> In this plugin is:
> js.src = '[https://connect.facebook.net/{$phfbchat_locale}/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1](https://connect.facebook.net/%7B$phfbchat_locale%7D/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1)';
> 
> If we change the parameters {$phfbchat_locale} to real localization, for example pl_PL - for Poland, like that:
> js.src = 'https://connect.facebook.net/pl_PL/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
> 
> this plugin works perfectly :-) and messenger plugin is appear :-)

**Comment by caito103** [comment]
This method doesnt work for me. I modified the text with es_LA but still not appearing. Did you restarted any service? Did you deactivated the module and then re-activated it? @fsadak What did you used in the parameter?

Thanks!
