### ISSUE TITLE
 communicator does not appear after fully setup on PS1.7.5

### ISSUE THREAD

**Issue by JanGorzycki** [kpodemski/phfbchat#9]
On a clean PS 1.7.5 installation, the messenger window is not shown after the setup

**Comment by JanGorzycki** [comment]
http://www.airgun.pl/

**Comment by kpodemski** [comment]
@JanGorzycki 

są teraz dwa wywołania messengera, jest wklejony kod z narzędzia Facebook oraz kod z pluginu, proponuje wyrzucić to wrzucone ręcznie, a żeby naprawić wyświetlanie samego modułu edytować ten plik na swoim serwerze:
`https://github.com/kpodemski/phfbchat/blob/master/views/templates/hook/footer.tpl`

i zmienić `{$phfbchat_locale}` na `pl_PL`
